updated 2016_ipdps_archer
soarlab/soarlab.github.io pull request #29
Opened 2020-02-07 07:04 UTC by Maryam81609

2020-02-07 16:09 UTC, zvonimir requested changes
Looks good, except that you are missing one image. Thx!

2020-02-07 16:09 UTC, zvonimir commented on _publications/2016_ipdps_agralslpm.md
> +image_large: 2016_ipdps_agralslpm.png
You are missing the `_teaser` image, which should be 1200x600.

2020-02-09 23:33 UTC, Maryam81609 commented
I added the teaser image. I can test it tomorrow on my machine in the lab.

2020-02-10 19:30 UTC, zvonimir approved these changes
Looks good to me.

2020-02-10 19:30 UTC, merged